---
aisex_addr: "http://www.aisex.com/bt/"
chaoliu_addr: "https://www.t66y.com/"
av_class:
  - chaoliu_asia_mosaiched
timeout: 60
topic_range: 128
save_path: "download"
hate_keywords:
like_keywords:
  - タイツ
  - パンスト
  - ストッキング
  - 护士
  - 護士
  - 看護婦
  - 看護師
  - ナース
  - 丝袜
  - 连裤袜
  - 白丝
  - 黑丝
  - 裤袜
  - 絲襪
  - 連褲襪
  - 褲襪
  - バレリーナ
  - バレエ
  - stocking
  - tights
  - 美腿
  - 美脚
proxy_addr: ""