---
aisex_addr: "http://www.aisex.com/bt/"
chaoliu_addr: "https://www.t66y.com/"
xp_addr : "http://h3.cnmbtgf.rocks/pw/"
av_class:
  - xp_asia_mosaiched
  - xp_asia_non_mosaiched
  - aicheng_asia_mosaiched
  - aicheng_asia_non_mosaicked
  - chaoliu_asia_mosaiched
  - chaoliu_asia_non_mosaiched
timeout: 60
topic_range: 256
save_path: "download"
hate_keywords:
like_keywords:
  - 美腿
  - 破处
proxy_addr: ""
